import { Router } from 'express';
import { db } from '../db/connection.js';

const router = Router();

// Builds a deterministic "AI daily summary" from today's seeded activity.
// In production this would be generated by an LLM reading the day's logs;
// here it is templated directly from the same aggregate queries so the
// demo console has a realistic digest without calling an external model.
router.get('/daily', (req, res) => {
    const cameraCount = db.prepare('SELECT COUNT(*) AS c FROM cameras').get().c;
    const detectionsToday = db.prepare(`
        SELECT COUNT(*) AS c FROM detections WHERE date(captured_at) = date('now', '-1 day')
    `).get().c;
    const detectionsTotal = db.prepare('SELECT COUNT(*) AS c FROM detections').get().c;

    const alertStats = db.prepare(`
        SELECT status, COUNT(*) AS c FROM alerts
        WHERE date(created_at) = date('now', '-1 day')
        GROUP BY status
    `).all();
    const topAlert = db.prepare(`
        SELECT a.plate_number, c.location, a.created_at FROM alerts a
        JOIN cameras c ON c.id = a.camera_id
        ORDER BY a.created_at DESC LIMIT 1
    `).get();

    const notificationStats = db.prepare(`
        SELECT type, COUNT(*) AS c FROM notifications
        WHERE date(sent_at) = date('now', '-1 day')
        GROUP BY type
    `).all();

    const corridorsGranted = db.prepare(`
        SELECT COUNT(*) AS c FROM green_corridor_events WHERE date(granted_at) = date('now', '-1 day')
    `).get().c;

    const tollStats = db.prepare(`
        SELECT n.name, COUNT(*) AS c FROM toll_transactions tx
        JOIN toll_nakas n ON n.id = tx.naka_id
        WHERE date(tx.occurred_at) = date('now', '-1 day') AND tx.status = 'reconciled'
        GROUP BY n.id ORDER BY c DESC LIMIT 1
    `).get();

    const confirmed = alertStats.find((a) => a.status === 'confirmed')?.c || 0;
    const dismissed = alertStats.find((a) => a.status === 'dismissed')?.c || 0;
    const open = alertStats.find((a) => a.status === 'open')?.c || 0;
    const insuranceNotices = notificationStats.find((n) => n.type === 'insurance')?.c || 0;
    const permitNotices = notificationStats.find((n) => n.type === 'permit')?.c || 0;
    const pucNotices = notificationStats.find((n) => n.type === 'puc')?.c || 0;

    const lines = [
        `${detectionsToday.toLocaleString()} plates read across ${cameraCount} cameras`,
        `${confirmed + dismissed + open} rogue-plate alerts — ${confirmed} confirmed, ${dismissed} dismissed${open ? `, ${open} open` : ''}`,
        topAlert ? `  ${topAlert.plate_number} · ${topAlert.location} · ${topAlert.created_at}` : null,
        `${insuranceNotices + permitNotices + pucNotices} expiry notices sent (insurance ${insuranceNotices}, permit ${permitNotices}, PUC ${pucNotices})`,
        `${corridorsGranted} green corridors granted to on-duty emergency vehicles`,
        tollStats ? `Toll naka ${tollStats.name}: ${tollStats.c.toLocaleString()} vehicles reconciled` : null,
    ].filter(Boolean);

    res.json({
        generatedAt: new Date().toISOString(),
        lines,
        totals: { detectionsTotal, detectionsToday, cameraCount },
    });
});

export default router;
